name: Docker Release Build

on:
  push:
    tags:
      - 'v*-alpha'
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Use .env.build instead of .env
        run: cp .env.build .env

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}-alpha,enable={{starts_with(github.ref, 'refs/tags/v') && ends_with(github.ref, '-alpha')}}
            type=raw,value=alpha,enable={{starts_with(github.ref, 'refs/tags/v') && ends_with(github.ref, '-alpha')}}
            type=semver,pattern={{version}},enable={{starts_with(github.ref, 'refs/tags/v') && !ends_with(github.ref, '-alpha')}}
            type=raw,value=latest,enable={{starts_with(github.ref, 'refs/tags/v') && !ends_with(github.ref, '-alpha')}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: run.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 
          platforms: linux/amd64,linux/arm64